imports:
    - { resource: 'http.yml' }

services:
    innmind_neo4j.dbal.connection.default:
        class: Innmind\Neo4j\DBAL\Connection
        public: false
        arguments:
            - '@innmind_neo4j.dbal.connection.transport'
            - '@innmind_neo4j.dbal.connection.transactions'

    innmind_neo4j.dbal.connection.logger:
        class: Innmind\Neo4j\DBAL\Connection\LoggerConnection
        public: false
        arguments:
            - '@innmind_neo4j.dbal.connection.default'
            - '@logger'
        tags:
            - { name: monolog.logger, channel: neo4j }

    innmind_neo4j.dbal.connection.transport:
        class: Innmind\Neo4j\DBAL\Transport\Http
        public: false
        arguments:
            - '@innmind_neo4j.dbal.connection.translator'
            - '@innmind_neo4j.dbal.connection.transport.http'

    innmind_neo4j.dbal.connection.transport.http:
        class: Innmind\Neo4j\DBAL\HttpTransport\Transport
        public: false
        arguments:
            - '@innmind_neo4j.dbal.connection.server'
            - '@innmind_neo4j.dbal.connection.authentication'
            - '@innmind_neo4j.http_transport.guzzle'

    innmind_neo4j.dbal.connection.translator:
        class: Innmind\Neo4j\DBAL\Translator\HttpTranslator
        public: false
        arguments:
            - '@innmind_neo4j.dbal.connection.transactions'

    innmind_neo4j.dbal.connection.transactions:
        class: Innmind\Neo4j\DBAL\Transactions
        public: false
        arguments:
            - '@innmind_neo4j.dbal.connection.transport.http'
            - ~

    innmind_neo4j.dbal.connection.server:
        class: Innmind\Neo4j\DBAL\Server
        public: false
        arguments:
            - ~
            - ~
            - ~

    innmind_neo4j.dbal.connection.authentication:
        class: Innmind\Neo4j\DBAL\Authentication
        public: false
        arguments:
            - ~
            - ~
