services:
    innmind_neo4j.http_transport.guzzle:
        class: Innmind\HttpTransport\GuzzleTransport
        public: false
        arguments:
            - '@innmind_neo4j.http_transport.guzzle.client'
            - '@innmind_neo4j.http.translator.response'

    innmind_neo4j.http_transport.guzzle.client:
        class: GuzzleHttp\Client
        public: false

    innmind_neo4j.http.translator.response:
        class: Innmind\Http\Translator\Response\Psr7Translator
        public: false
        arguments:
            - '@innmind_neo4j.http.header_factory'

    innmind_neo4j.http.header_factory:
        class: Innmind\Http\Factory\Header\TryFactory
        public: false
        factory:
            - Innmind\Http\Factory\Header\Factories
            - default
