imports:
    - { resource: 'services/dbal.yml' }
    - { resource: 'services/persisters.yml' }
    - { resource: 'services/entity_factories.yml' }
    - { resource: 'services/metadatas.yml' }
    - { resource: 'services/translators.yml' }
    - { resource: 'services/entity.yml' }

services:
    innmind_neo4j.clock:
        class: Innmind\TimeContinuum\TimeContinuum\Earth
        public: false

    innmind_neo4j.event_bus.null:
        class: Innmind\EventBus\NullEventBus
        public: false

    innmind_neo4j.manager:
        class: Innmind\Neo4j\ONM\Manager\Manager
        public: true
        arguments:
            - '@innmind_neo4j.unit_of_work'
            - '@innmind_neo4j.metadatas'
            - '@innmind_neo4j.repository_factory'
            - '@innmind_neo4j.generators'

    innmind_neo4j.unit_of_work:
        class: Innmind\Neo4j\ONM\UnitOfWork
        arguments:
            - '@innmind_neo4j.dbal.connection'
            - '@innmind_neo4j.entity_container'
            - '@innmind_neo4j.entity_factory'
            - '@innmind_neo4j.translator.identity_match'
            - '@innmind_neo4j.metadatas'
            - ~
            - '@innmind_neo4j.generators'
        public: false

    innmind_neo4j.entity_container:
        class: Innmind\Neo4j\ONM\Entity\Container
        public: false

    innmind_neo4j.generators:
        class: Innmind\Neo4j\ONM\Identity\Generators
        public: false
        arguments:
            - Innmind\Neo4j\ONM\Identity\Generators
            - Innmind\Neo4j\ONM\Identity\Generator
            - []
        factory:
            - Innmind\Neo4jBundle\Factory\MapFactory
            - make

    innmind_neo4j.types:
        class: Innmind\Neo4j\ONM\Types
        public: false

    innmind_neo4j.repository_factory:
        class: Innmind\Neo4j\ONM\RepositoryFactory
        arguments:
            - '@innmind_neo4j.unit_of_work'
            - '@innmind_neo4j.translator.match'
            - '@innmind_neo4j.translator.specification'
        public: false
        configurator:
            - '@innmind_neo4j.repository_factory.configurator'
            - configure

    innmind_neo4j.repository_factory.configurator:
        class: Innmind\Neo4jBundle\Configurator\RepositoryFactoryConfigurator
        arguments:
            - '@innmind_neo4j.metadatas'
        public: false


